baseURL = 'https://thunderview.net/'
languageCode = 'en-us'
title = 'Thunder View'
theme = ["risotto"]
enableInlineShortcodes = true
timeout = "90s"

[mediaTypes]
  [mediaTypes.'application/json']
    suffixes = ['blkx']
  
[markup.goldmark.renderer]
  unsafe= true